# from 32 -> 64 ffhq config (adapted from bsr_sr, official source config superresolution), use ffhq64 AE model, 32x32x3 upsampled to 64x64x3, and encode to 16x16x3
model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: /home/zhren/Charlie/charlie-latent-diffusion/latent-diffusion/logs/2023-02-02T10-39-31_ffhq32-64_sr/checkpoints/epoch=000014.ckpt
    linear_start: 0.0015
    linear_end: 0.0155
    log_every_t: 100
    timesteps: 1000 # original 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: LR_image
    image_size: 32
    channels: 3 # original 3, now 8; 8 is the latent space channels (embedding size), because 3 x 32 x 32
    cond_stage_trainable: false
    concat_mode: true
    monitor: val/loss
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 6 # original 6, now 3 + 3, but it's not working since embedding and image need same dimension
        out_channels: 3 # original 3, now 8, 1-to-1 correspondence with channels
        model_channels: 160
        attention_resolutions:
          - 16
          - 8
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 2
          - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: /home/zhren/Charlie/charlie-latent-diffusion/latent-diffusion/logs/2023-01-31T21-11-20_vq-f2-64/checkpoints/epoch=000168.ckpt
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 64
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
            - 1
            - 2
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: torch.nn.Identity
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 5
    wrap: false
    train:
      target: taming.data.ffhq.FFHQSRTrain
      params:
        size: 64
        degradation: bsrgan_light
        downscale_f: 2
        min_crop_f: 0.5
        max_crop_f: 1.0
        random_crop: true
    validation:
      target: taming.data.ffhq.FFHQSRValidation
      params:
        size: 64
        degradation: bsrgan_light
        downscale_f: 2
        min_crop_f: 0.5
        max_crop_f: 1.0
        random_crop: true
